repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: v0.1.2
    hooks:
      - id: uv
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff
      - id: ruff-format
