# get_object { #quartodoc.get_object }

```python
get_object(
    path,
    object_name=None,
    parser='numpy',
    load_aliases=True,
    dynamic=False,
    loader=None,
)
```

Fetch a griffe object.

## Parameters {.doc-section .doc-section-parameters}

| Name         | Type            | Description                                                                                                                                            | Default    |
|--------------|-----------------|--------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| path         | str             | An import path to the object. This should have the form `path.to.module:object`. For example, `quartodoc:get_object` or `quartodoc:MdRenderer.render`. | _required_ |
| object_name  | \'str \| None\' | (Deprecated). A function name.                                                                                                                         | `None`     |
| parser       | str             | A docstring parser to use.                                                                                                                             | `'numpy'`  |
| load_aliases |                 | For aliases that were imported from other modules, should we load that module?                                                                         | `True`     |
| dynamic      |                 | Whether to dynamically import object. Useful if docstring is not hard-coded, but was set on object by running python code.                             | `False`    |

## See Also {.doc-section .doc-section-see-also}

preview: print a user-friendly preview of a griffe object.

## Examples {.doc-section .doc-section-examples}

```python
>>> get_function("quartodoc", "get_function")
<Function('get_function', ...
```

## Returns {.doc-section .doc-section-returns}

| Name   | Type      | Description   |
|--------|-----------|---------------|
| x      | dc.Object | abc           |